### ISSUE TITLE
Markdown broken at continue

### ISSUE THREAD

**Issue by bet0x** [MEDIA76/arcane-blog#5]
Expected result: Article with the continue link. 

You can see the result in here: https://www.barrahome.org/

It works when you go and read the entire article: 
https://www.barrahome.org/post/centos-apache-selinux/

Actual result: Article without continue link, parsed inside the code block.

Markdown code: https://github.com/bet0x/barrahome/blob/1e5c5ebe1713e0bcb2e8022f3858d9371b2859ab/pages/posts/centos-apache-selinux.md

**Comment by capachow** [comment]
This bug should be now fixed. This was caused due to the fact that the `.md` content was being truncated in the middle of the `<pre><code>` section. Which placed the continue button right inside that preformatted section so then the markdown helper _correctly_ ignored it.

To fix this, I redesigned how the post previews are being generated and rendered. I now take the first non-heading line from the `.md` content. Then it runs just that one line through the markdown helper, then a `strip_tags()`, and then truncate for a nice a clean slice. The continue button is now rendered outside the markdown helper via a newly added anchor helper.

I have thoroughly tested various combinations, but if you still experience issues, please reopen. 👍.

_P.S. This was not the only case that caused this bug to happen. Links were being cut in the middle of their URL because of truncating before running though the markdown helper. Same for any inline formatting. So this was a must fix bug._
